{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-09-24 16:39:24.809 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.406 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\91909\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2024-09-24 16:39:25.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.423 Session state does not function when running a script without `streamlit run`\n",
      "2024-09-24 16:39:25.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.437 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.453 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-24 16:39:25.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pickle\n",
    "import pandas as pd\n",
    "#from flask import Flask, request  # Flask and request were missing imports\n",
    "#from flasgger import Swagger\n",
    "import streamlit as st \n",
    "from PIL import Image\n",
    "\n",
    "# Initialize the Flask app\n",
    "#app = Flask(__name__)  # Flask name initialization was incorrect\n",
    "#Swagger(app)\n",
    "\n",
    "# Load the pre-trained classifier from the pickle file\n",
    "pickle_in = open(\"f.pkl\", \"rb\")\n",
    "classifier = pickle.load(pickle_in)\n",
    "\n",
    "# Define the welcome route\n",
    "#@app.route('/')\n",
    "def welcome():\n",
    "    return \"Welcome All\"\n",
    "\n",
    "# Define the predict_flower route using GET method\n",
    "#@app.route('/predict', methods=[\"GET\"])\n",
    "def predict_flower():\n",
    "    \"\"\"\n",
    "    Let's predict the iris flower\n",
    "    This is using docstrings for specifications.\n",
    "    ---\n",
    "    parameters:  \n",
    "      - name: sepal_length\n",
    "        in: query\n",
    "        type: number\n",
    "        required: true\n",
    "      - name: sepal_width\n",
    "        in: query\n",
    "        type: number\n",
    "        required: true\n",
    "      - name: petal_length\n",
    "        in: query\n",
    "        type: number\n",
    "        required: true\n",
    "      - name: petal_width\n",
    "        in: query\n",
    "        type: number\n",
    "        required: true\n",
    "    responses:\n",
    "        200:\n",
    "            description: The output values\n",
    "    \"\"\"\n",
    "    # Getting the input values from the request\n",
    "    sepal_length = float(request.args.get(\"sepal_length\"))\n",
    "    sepal_width = float(request.args.get(\"sepal_width\"))\n",
    "    petal_length = float(request.args.get(\"petal_length\"))\n",
    "    petal_width = float(request.args.get(\"petal_width\"))\n",
    "    \n",
    "    # Making a prediction\n",
    "    prediction = classifier.predict([[sepal_length, sepal_width, petal_length, petal_width]])\n",
    "    \n",
    "    return f\"The predicted class is {prediction[0]}\"\n",
    "\n",
    "# Streamlit app function\n",
    "def main():\n",
    "    st.title(\"Iris Flower Prediction\")\n",
    "    html_temp = \"\"\"\n",
    "    <div style=\"background-color:tomato;padding:10px\">\n",
    "    <h2 style=\"color:white;text-align:center;\">Iris Flower Prediction ML App </h2>\n",
    "    </div>\n",
    "    \"\"\"\n",
    "    st.markdown(html_temp, unsafe_allow_html=True)\n",
    "\n",
    "    # Input fields in Streamlit\n",
    "    sepal_length = st.text_input(\"Sepal Length\", \"Type Here\")\n",
    "    sepal_width = st.text_input(\"Sepal Width\", \"Type Here\")\n",
    "    petal_length = st.text_input(\"Petal Length\", \"Type Here\")\n",
    "    petal_width = st.text_input(\"Petal Width\", \"Type Here\")\n",
    "    \n",
    "    result = \"\"\n",
    "    \n",
    "    # Prediction button in Streamlit\n",
    "    if st.button(\"Predict\"):\n",
    "        result = predict_flower(sepal_length, sepal_width, petal_length, petal_width)\n",
    "        st.success(f'The output is {result}')\n",
    "    \n",
    "    if st.button(\"About\"):\n",
    "        st.text(\"Let's Learn\")\n",
    "        st.text(\"Built with Streamlit\")\n",
    "        \n",
    "if __name__ == '__main__':\n",
    "    main()\n",
    "        "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
